services:
  frontend-vue:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # --- AJOUT ICI ---
      args:
        VITE_API_URL: https://piedssansfrontieres.ch/api
      # -----------------
    container_name: vue_frontend_prod
    restart: always
    # Pas de ports, on reste en interne
    networks:
      - web-network

networks:
  web-network:
    external: true
