# ETAPE 1 : Build (On utilise Node juste pour compiler)
FROM node:22-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ETAPE 2 : Production (On utilise Nginx pour servir)
FROM nginx:1.29.4-alpine as production-stage

# On copie le code compilé (dossier dist) depuis l'étape 1
COPY --from=build-stage /app/dist /usr/share/nginx/html

# On copie ta configuration nginx personnalisée (celle créée au point 1)
COPY nginx.vue.conf /etc/nginx/conf.d/default.conf

EXPOSE 2002
CMD ["nginx", "-g", "daemon off;"]
