# ETAPE 1 : Build
FROM node:22-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# --- AJOUT ICI ---
# On déclare qu'on attend un argument
ARG VITE_API_URL 
# On transforme cet argument en variable d'environnement pour que Vite le voie
ENV VITE_API_URL=$VITE_API_URL
# -----------------

RUN npm run build

# ETAPE 2 : Production
FROM nginx:1.29.4-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.vue.conf /etc/nginx/conf.d/default.conf
# Pas de EXPOSE ici, c'est de la doc, ce qui compte c'est le nginx.conf
CMD ["nginx", "-g", "daemon off;"]
