server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # La ligne magique pour les SPA (Single Page Applications) :
        # Si le fichier n'existe pas, renvoie index.html au lieu d'une 404
        try_files $uri $uri/ /index.html;
    }

    # Gestion des erreurs 50x
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
